export const books = [
  {
    id: '1',
    title: '百年孤独',
    author: '加西亚·马尔克斯',
    category: '文学小说',
    badge: '热销',
    stars: '★★★★★',
    ratingNum: '4.9',
    ratingCount: '(12,847 人评价)',
    price: '¥49.00',
    originalPrice: '¥68.00',
    description: '《百年孤独》是魔幻现实主义文学的代表作，描写了布恩迪亚家族七代人的传奇故事，以及加勒比海沿岸小镇马孔多的百年兴衰，反映了拉丁美洲一个世纪以来风云变幻的历史。',
    intro: '《百年孤独》内容复杂，人物众多，情节离奇，手法新颖。马尔克斯在布恩迪亚家族中反复地用同一个名字，为读者造成极大的困扰。然而，正是这种独特的命名方式，象征着这个家族百年来的孤独与轮回。',
    authorBio: '加夫列尔·加西亚·马尔克斯（Gabriel García Márquez，1927-2014），哥伦比亚作家、记者和社会活动家，拉丁美洲魔幻现实主义文学的代表人物，20世纪最有影响力的作家之一，1982年诺贝尔文学奖得主。',
    info: { '出版社': '南海出版公司', '出版日期': '2017年8月', '页数': '360页', 'ISBN': '978-7-5442-7115-3', '装帧': '精装' },
    coverImg: '/images/100-years-of-solitude.jpg',
    coverEmoji: '📖'
  },
  {
    id: '2',
    title: '人类简史：从动物到上帝',
    author: '尤瓦尔·赫拉利',
    category: '历史社科',
    badge: '新品',
    stars: '★★★★☆',
    ratingNum: '4.8',
    ratingCount: '(9,523 人评价)',
    price: '¥68.00',
    originalPrice: '¥88.00',
    description: '《人类简史》是一部宏大的人类进化史叙事。作者以深刻的洞察力，讲述了从大约135亿年前的宇宙大爆炸到21世纪的人类历史，涵盖了认知革命、农业革命、人类的融合统一与科学革命等重大历史节点。',
    intro: '这是一部宏大的人类进化史。作者从认知革命、农业革命、人类的融合统一、科学革命四个维度，讲述了人类从动物界脱颖而出的历程，揭示了人类如何成为地球的主宰，以及未来可能的走向。',
    authorBio: '尤瓦尔·赫拉利（Yuval Noah Harari），1976年生，以色列历史学家，耶路撒冷希伯来大学历史系教授，专注于世界历史和宏观历史进程研究。',
    info: { '出版社': '中信出版社', '出版日期': '2016年9月', '页数': '432页', 'ISBN': '978-7-5086-6073-6', '装帧': '��装' },
    coverImg: '/images/sapiens.jpg',
    coverEmoji: '📕'
  },
  {
    id: '3',
    title: '活着',
    author: '余华',
    category: '文学小说',
    badge: '',
    stars: '★★★★★',
    ratingNum: '4.9',
    ratingCount: '(15,234 人评价)',
    price: '¥35.00',
    originalPrice: '¥45.00',
    description: '《活着》讲述了农村人福贵悲惨的人生遭遇。福贵本是个阔少爷，可他嗜赌如命，终于赌光了家业，一贫如洗。',
    intro: '《活着》是一篇读起来让人感到沉重的小说。余华用平实的语言讲述了一个农民家庭在时代变迁中的苦难历程。',
    authorBio: '余华，1960年生，浙江海盐人，中国当代著名作家。代表作品有《活着》《许三观卖血记》《兄弟》等。',
    info: { '出版社': '作家出版社', '出版日期': '2012年8月', '页数': '191页', 'ISBN': '978-7-5063-6549-9', '装帧': '平装' },
    coverImg: '/images/to-live.jpg',
    coverEmoji: '📗'
  },
  {
    id: '4',
    title: '三体（全集）',
    author: '刘慈欣',
    category: '科幻小说',
    badge: '促销',
    stars: '★★★★★',
    ratingNum: '4.9',
    ratingCount: '(18,672 人评价)',
    price: '¥89.00',
    originalPrice: '¥118.00',
    description: '《三体》讲述了地球人类文明和三体文明之间的信息交流、生死搏杀及两个文明在宇宙中的兴衰历程。',
    intro: '文化大革命期间，天体物理学家叶文洁向三体世界发出了地球文明的第一声啼鸣。四光年外的三体文明接收到了信号，开始入侵地球。',
    authorBio: '刘慈欣，1963年生，山西阳泉人，中国科幻小说代表作家，高级工程师。2015年凭借《三体》获雨果奖最佳长篇故事奖。',
    info: { '出版社': '重庆出版社', '出版日期': '2010年11月', '页数': '930页', 'ISBN': '978-7-229-03026-9', '装帧': '精装' },
    coverImg: '/images/three-body.jpg',
    coverEmoji: '📘'
  },
  {
    id: '5',
    title: '思考，快与慢',
    author: '丹尼尔·卡尼曼',
    category: '心理学',
    badge: '',
    stars: '★★★★☆',
    ratingNum: '4.7',
    ratingCount: '(7,891 人评价)',
    price: '¥55.00',
    originalPrice: '¥68.00',
    description: '诺贝尔经济学奖得主丹尼尔·卡尼曼的代表作，揭示了人类思维的双系统——快速、直觉的系统1和缓慢、理性的系统2。',
    intro: '卡尼曼在书中系统性地介绍了影响人类思维的两大系统：系统1（快思考）和系统2（慢思考）。',
    authorBio: '丹尼尔·卡尼曼（Daniel Kahneman，1934-2024），以色列裔美国心理学家，2002年诺贝尔经济学奖得主。',
    info: { '出版社': '中信出版社', '出版日期': '2012年7月', '页数': '396页', 'ISBN': '978-7-5086-3452-4', '装帧': '平装' },
    coverImg: '/images/thinking-fast-slow.jpg',
    coverEmoji: '📙'
  },
  {
    id: '6',
    title: '小王子',
    author: '安托万·德·圣-埃克苏佩里',
    category: '童话寓言',
    badge: '',
    stars: '★★★★★',
    ratingNum: '4.9',
    ratingCount: '(22,456 人评价)',
    price: '¥29.00',
    originalPrice: '¥38.00',
    description: '《小王子》是法国作家安托万·德·圣-埃克苏佩里于1942年写成的著名儿童文学短篇小说。',
    intro: '小王子离开自己的星球后，相继拜访了多个星球，最终来到了地球。他与狐狸的相遇让他懂得了什么是真正的友谊和爱情。',
    authorBio: '安托万·德·圣-埃克苏佩里（Antoine de Saint-Exupéry，1900-1944），法国作家、飞行员。',
    info: { '出版社': '人民文学出版社', '出版日期': '2003年7月', '页数': '109页', 'ISBN': '978-7-0200-5347-7', '装帧': '平装' },
    coverImg: '/images/little-prince.jpg',
    coverEmoji: '📔'
  },
  {
    id: '7',
    title: '设计中的设计',
    author: '原研哉',
    category: '设计艺术',
    badge: '新品',
    stars: '★★★★☆',
    ratingNum: '4.6',
    ratingCount: '(5,678 人评价)',
    price: '¥78.00',
    originalPrice: '¥98.00',
    description: '原研哉是日本著名平面设计大师，他在这本书中系统梳理了设计的本质，提出了"RE-DESIGN"的概念。',
    intro: '本书是原研哉在武藏野美术大学的基础设计讲座整理而成。他从设计的原点出发，探讨了如何通过设计思维重新审视日常生活中的物品。',
    authorBio: '原研哉（Kenya Hara），1958年生，日本著名平面设计大师，武藏野美术大学教授，无印良品艺术总监。',
    info: { '出版社': '山东人民出版社', '出版日期': '2006年10月', '页数': '224页', 'ISBN': '978-7-209-04077-2', '装帧': '平装' },
    coverImg: '/images/design-of-design.jpg',
    coverEmoji: '📓'
  },
  {
    id: '8',
    title: '追风筝的人',
    author: '卡勒德·胡赛尼',
    category: '文学小说',
    badge: '',
    stars: '★★★★★',
    ratingNum: '4.8',
    ratingCount: '(14,321 人评价)',
    price: '¥36.00',
    originalPrice: '¥48.00',
    description: '《追风筝的人》讲述了一个关于友谊、背叛与救赎的故事。',
    intro: '故事以阿富汗的历史变迁为背景，通过阿米尔的视角，展现了人性的复杂与挣扎。',
    authorBio: '卡勒德·胡赛尼（Khaled Hosseini），1965年生，阿富汗裔美国作家、医生。',
    info: { '出版社': '上海人民出版社', '出版日期': '2006年9月', '页数': '362页', 'ISBN': '978-7-2080-6431-4', '装帧': '平装' },
    coverImg: '/images/kite-runner.jpg',
    coverEmoji: '📒'
  }
];

export const getBookById = (id) => books.find(book => book.id === id);